In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [8]:
### Sentences
sent = ['the glass of milk',
       'the glass of juice',
       'the cup of tea',
       'I am a good boy',
       'I am a good developer',
       'understand the meaning of words',
       'your videos are good']

In [9]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [10]:
## Define the vocabulary size
voc_size = 10000

In [11]:
## One Hot Representaion
one_hot_repr = [one_hot(words,voc_size)for words in sent]
one_hot_repr

[[862, 4709, 5929, 4724],
 [862, 4709, 5929, 5542],
 [862, 271, 5929, 8009],
 [7745, 352, 7071, 5586, 1845],
 [7745, 352, 7071, 5586, 2568],
 [1680, 862, 7485, 5929, 4630],
 [3312, 4291, 7738, 5586]]

In [12]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing .sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [13]:
import numpy as np

In [17]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  862 4709 5929 4724]
 [   0    0    0    0  862 4709 5929 5542]
 [   0    0    0    0  862  271 5929 8009]
 [   0    0    0 7745  352 7071 5586 1845]
 [   0    0    0 7745  352 7071 5586 2568]
 [   0    0    0 1680  862 7485 5929 4630]
 [   0    0    0    0 3312 4291 7738 5586]]


In [16]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr,padding='post',maxlen=sent_length)
print(embedded_docs)

[[ 862 4709 5929 4724    0    0    0    0]
 [ 862 4709 5929 5542    0    0    0    0]
 [ 862  271 5929 8009    0    0    0    0]
 [7745  352 7071 5586 1845    0    0    0]
 [7745  352 7071 5586 2568    0    0    0]
 [1680  862 7485 5929 4630    0    0    0]
 [3312 4291 7738 5586    0    0    0    0]]


In [18]:
## Feature representation
dim = 10

In [21]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [22]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 324ms/step


array([[[-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,
          0.04556136,  0.01381161,  0.01154869,  0.02133859,
         -0.04275189, -0.01689749],
        [-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,
          0.04556136,  0.01381161,  0.01154869,  0.02133859,
         -0.04275189, -0.01689749],
        [-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,
          0.04556136,  0.01381161,  0.01154869,  0.02133859,
         -0.04275189, -0.01689749],
        [-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,
          0.04556136,  0.01381161,  0.01154869,  0.02133859,
         -0.04275189, -0.01689749],
        [ 0.0165905 ,  0.00900597,  0.01631546, -0.02685435,
         -0.02338182,  0.0078678 ,  0.02584699,  0.0209395 ,
          0.02986496, -0.04562776],
        [-0.03161804,  0.00408477,  0.04336829, -0.03393646,
         -0.00797559, -0.03801681,  0.04066027,  0.04793924,
          0.02384866,  0.01118473],
        [-0.00989989,  0.0162685 ,  0.04405225, -0.0

In [24]:
embedded_docs[0]

array([   0,    0,    0,    0,  862, 4709, 5929, 4724])

In [25]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 85ms/step


array([[-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,  0.04556136,
         0.01381161,  0.01154869,  0.02133859, -0.04275189, -0.01689749],
       [-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,  0.04556136,
         0.01381161,  0.01154869,  0.02133859, -0.04275189, -0.01689749],
       [-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,  0.04556136,
         0.01381161,  0.01154869,  0.02133859, -0.04275189, -0.01689749],
       [-0.00236471, -0.01359332,  0.00597204,  0.0484989 ,  0.04556136,
         0.01381161,  0.01154869,  0.02133859, -0.04275189, -0.01689749],
       [ 0.0165905 ,  0.00900597,  0.01631546, -0.02685435, -0.02338182,
         0.0078678 ,  0.02584699,  0.0209395 ,  0.02986496, -0.04562776],
       [-0.03161804,  0.00408477,  0.04336829, -0.03393646, -0.00797559,
        -0.03801681,  0.04066027,  0.04793924,  0.02384866,  0.01118473],
       [-0.00989989,  0.0162685 ,  0.04405225, -0.00050533,  0.04058457,
         0.04295817, -0.02276978, -0.00852877